package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CreancierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreancierAllPropertiesEquals(Creancier expected, Creancier actual) {
        assertCreancierAutoGeneratedPropertiesEquals(expected, actual);
        assertCreancierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreancierAllUpdatablePropertiesEquals(Creancier expected, Creancier actual) {
        assertCreancierUpdatableFieldsEquals(expected, actual);
        assertCreancierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreancierAutoGeneratedPropertiesEquals(Creancier expected, Creancier actual) {
        assertThat(actual)
            .as("Verify Creancier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreancierUpdatableFieldsEquals(Creancier expected, Creancier actual) {
        assertThat(actual)
            .as("Verify Creancier relevant properties")
            .satisfies(a -> assertThat(a.getNir()).as("check nir").isEqualTo(expected.getNir()))
            .satisfies(a -> assertThat(a.getCleNir()).as("check cleNir").isEqualTo(expected.getCleNir()))
            .satisfies(a -> assertThat(a.getNumAllocCristal()).as("check numAllocCristal").isEqualTo(expected.getNumAllocCristal()))
            .satisfies(a ->
                assertThat(a.getNumPersonneCristal()).as("check numPersonneCristal").isEqualTo(expected.getNumPersonneCristal())
            )
            .satisfies(a ->
                assertThat(a.getCodeOrganismeCristal()).as("check codeOrganismeCristal").isEqualTo(expected.getCodeOrganismeCristal())
            )
            .satisfies(a ->
                assertThat(a.getSituationFamilialeDebutDate())
                    .as("check situationFamilialeDebutDate")
                    .isEqualTo(expected.getSituationFamilialeDebutDate())
            )
            .satisfies(a ->
                assertThat(a.getCodeSituationFamiliale()).as("check codeSituationFamiliale").isEqualTo(expected.getCodeSituationFamiliale())
            )
            .satisfies(a -> assertThat(a.getCodeNationalite()).as("check codeNationalite").isEqualTo(expected.getCodeNationalite()))
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCreancierUpdatableRelationshipsEquals(Creancier expected, Creancier actual) {
        // empty method
    }
}
