package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DebiteurAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebiteurAllPropertiesEquals(Debiteur expected, Debiteur actual) {
        assertDebiteurAutoGeneratedPropertiesEquals(expected, actual);
        assertDebiteurAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebiteurAllUpdatablePropertiesEquals(Debiteur expected, Debiteur actual) {
        assertDebiteurUpdatableFieldsEquals(expected, actual);
        assertDebiteurUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebiteurAutoGeneratedPropertiesEquals(Debiteur expected, Debiteur actual) {
        assertThat(actual)
            .as("Verify Debiteur auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebiteurUpdatableFieldsEquals(Debiteur expected, Debiteur actual) {
        assertThat(actual)
            .as("Verify Debiteur relevant properties")
            .satisfies(a -> assertThat(a.getNir()).as("check nir").isEqualTo(expected.getNir()))
            .satisfies(a -> assertThat(a.getCleNir()).as("check cleNir").isEqualTo(expected.getCleNir()))
            .satisfies(a -> assertThat(a.getNumAllocCristal()).as("check numAllocCristal").isEqualTo(expected.getNumAllocCristal()))
            .satisfies(a ->
                assertThat(a.getCodeOrganismeCristal()).as("check codeOrganismeCristal").isEqualTo(expected.getCodeOrganismeCristal())
            )
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDebiteurUpdatableRelationshipsEquals(Debiteur expected, Debiteur actual) {
        // empty method
    }
}
