package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DefaillanceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaillanceAllPropertiesEquals(Defaillance expected, Defaillance actual) {
        assertDefaillanceAutoGeneratedPropertiesEquals(expected, actual);
        assertDefaillanceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaillanceAllUpdatablePropertiesEquals(Defaillance expected, Defaillance actual) {
        assertDefaillanceUpdatableFieldsEquals(expected, actual);
        assertDefaillanceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaillanceAutoGeneratedPropertiesEquals(Defaillance expected, Defaillance actual) {
        assertThat(actual)
            .as("Verify Defaillance auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaillanceUpdatableFieldsEquals(Defaillance expected, Defaillance actual) {
        assertThat(actual)
            .as("Verify Defaillance relevant properties")
            .satisfies(a -> assertThat(a.getMoisDefaillance()).as("check moisDefaillance").isEqualTo(expected.getMoisDefaillance()))
            .satisfies(a ->
                assertThat(a.getMontantPADue())
                    .as("check montantPADue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantPADue())
            )
            .satisfies(a ->
                assertThat(a.getMontantPAVersee())
                    .as("check montantPAVersee")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMontantPAVersee())
            )
            .satisfies(a -> assertThat(a.getFlagDetteInitiale()).as("check flagDetteInitiale").isEqualTo(expected.getFlagDetteInitiale()))
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDefaillanceUpdatableRelationshipsEquals(Defaillance expected, Defaillance actual) {
        assertThat(actual)
            .as("Verify Defaillance relationships")
            .satisfies(a -> assertThat(a.getDossier()).as("check dossier").isEqualTo(expected.getDossier()));
    }
}
