package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DemarcheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemarcheAllPropertiesEquals(Demarche expected, Demarche actual) {
        assertDemarcheAutoGeneratedPropertiesEquals(expected, actual);
        assertDemarcheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemarcheAllUpdatablePropertiesEquals(Demarche expected, Demarche actual) {
        assertDemarcheUpdatableFieldsEquals(expected, actual);
        assertDemarcheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemarcheAutoGeneratedPropertiesEquals(Demarche expected, Demarche actual) {
        assertThat(actual)
            .as("Verify Demarche auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemarcheUpdatableFieldsEquals(Demarche expected, Demarche actual) {
        assertThat(actual)
            .as("Verify Demarche relevant properties")
            .satisfies(a -> assertThat(a.getDemarcheDate()).as("check demarcheDate").isEqualTo(expected.getDemarcheDate()))
            .satisfies(a -> assertThat(a.getNumDemarche()).as("check numDemarche").isEqualTo(expected.getNumDemarche()))
            .satisfies(a -> assertThat(a.getCodeOrigine()).as("check codeOrigine").isEqualTo(expected.getCodeOrigine()))
            .satisfies(a -> assertThat(a.getCodeStatut()).as("check codeStatut").isEqualTo(expected.getCodeStatut()))
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDemarcheUpdatableRelationshipsEquals(Demarche expected, Demarche actual) {
        assertThat(actual)
            .as("Verify Demarche relationships")
            .satisfies(a -> assertThat(a.getDossier()).as("check dossier").isEqualTo(expected.getDossier()));
    }
}
