package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DossierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierAllPropertiesEquals(Dossier expected, Dossier actual) {
        assertDossierAutoGeneratedPropertiesEquals(expected, actual);
        assertDossierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierAllUpdatablePropertiesEquals(Dossier expected, Dossier actual) {
        assertDossierUpdatableFieldsEquals(expected, actual);
        assertDossierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierAutoGeneratedPropertiesEquals(Dossier expected, Dossier actual) {
        assertThat(actual)
            .as("Verify Dossier auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierUpdatableFieldsEquals(Dossier expected, Dossier actual) {
        assertThat(actual)
            .as("Verify Dossier relevant properties")
            .satisfies(a -> assertThat(a.getNumDossierNor()).as("check numDossierNor").isEqualTo(expected.getNumDossierNor()))
            .satisfies(a -> assertThat(a.getNumDossierGaia()).as("check numDossierGaia").isEqualTo(expected.getNumDossierGaia()))
            .satisfies(a -> assertThat(a.getReceptionDateNor()).as("check receptionDateNor").isEqualTo(expected.getReceptionDateNor()))
            .satisfies(a -> assertThat(a.getValidationDateNor()).as("check validationDateNor").isEqualTo(expected.getValidationDateNor()))
            .satisfies(a -> assertThat(a.getCodeOrganisme()).as("check codeOrganisme").isEqualTo(expected.getCodeOrganisme()))
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDossierUpdatableRelationshipsEquals(Dossier expected, Dossier actual) {
        assertThat(actual)
            .as("Verify Dossier relationships")
            .satisfies(a -> assertThat(a.getDebiteur()).as("check debiteur").isEqualTo(expected.getDebiteur()))
            .satisfies(a -> assertThat(a.getCreancier()).as("check creancier").isEqualTo(expected.getCreancier()));
    }
}
