package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnfantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfantAllPropertiesEquals(Enfant expected, Enfant actual) {
        assertEnfantAutoGeneratedPropertiesEquals(expected, actual);
        assertEnfantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfantAllUpdatablePropertiesEquals(Enfant expected, Enfant actual) {
        assertEnfantUpdatableFieldsEquals(expected, actual);
        assertEnfantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfantAutoGeneratedPropertiesEquals(Enfant expected, Enfant actual) {
        assertThat(actual)
            .as("Verify Enfant auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfantUpdatableFieldsEquals(Enfant expected, Enfant actual) {
        assertThat(actual)
            .as("Verify Enfant relevant properties")
            .satisfies(a -> assertThat(a.getNir()).as("check nir").isEqualTo(expected.getNir()))
            .satisfies(a -> assertThat(a.getCleNir()).as("check cleNir").isEqualTo(expected.getCleNir()))
            .satisfies(a -> assertThat(a.getNumPersonneGaia()).as("check numPersonneGaia").isEqualTo(expected.getNumPersonneGaia()))
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnfantUpdatableRelationshipsEquals(Enfant expected, Enfant actual) {
        assertThat(actual)
            .as("Verify Enfant relationships")
            .satisfies(a -> assertThat(a.getDossier()).as("check dossier").isEqualTo(expected.getDossier()));
    }
}
