package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RechercheSolvableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechercheSolvableAllPropertiesEquals(RechercheSolvable expected, RechercheSolvable actual) {
        assertRechercheSolvableAutoGeneratedPropertiesEquals(expected, actual);
        assertRechercheSolvableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechercheSolvableAllUpdatablePropertiesEquals(RechercheSolvable expected, RechercheSolvable actual) {
        assertRechercheSolvableUpdatableFieldsEquals(expected, actual);
        assertRechercheSolvableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechercheSolvableAutoGeneratedPropertiesEquals(RechercheSolvable expected, RechercheSolvable actual) {
        assertThat(actual)
            .as("Verify RechercheSolvable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechercheSolvableUpdatableFieldsEquals(RechercheSolvable expected, RechercheSolvable actual) {
        assertThat(actual)
            .as("Verify RechercheSolvable relevant properties")
            .satisfies(a ->
                assertThat(a.getRechercheSolvabiliteDebutDate())
                    .as("check rechercheSolvabiliteDebutDate")
                    .isEqualTo(expected.getRechercheSolvabiliteDebutDate())
            )
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRechercheSolvableUpdatableRelationshipsEquals(RechercheSolvable expected, RechercheSolvable actual) {
        assertThat(actual)
            .as("Verify RechercheSolvable relationships")
            .satisfies(a -> assertThat(a.getDebiteur()).as("check debiteur").isEqualTo(expected.getDebiteur()));
    }
}
