package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResultatSolvableAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatSolvableAllPropertiesEquals(ResultatSolvable expected, ResultatSolvable actual) {
        assertResultatSolvableAutoGeneratedPropertiesEquals(expected, actual);
        assertResultatSolvableAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatSolvableAllUpdatablePropertiesEquals(ResultatSolvable expected, ResultatSolvable actual) {
        assertResultatSolvableUpdatableFieldsEquals(expected, actual);
        assertResultatSolvableUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatSolvableAutoGeneratedPropertiesEquals(ResultatSolvable expected, ResultatSolvable actual) {
        assertThat(actual)
            .as("Verify ResultatSolvable auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatSolvableUpdatableFieldsEquals(ResultatSolvable expected, ResultatSolvable actual) {
        assertThat(actual)
            .as("Verify ResultatSolvable relevant properties")
            .satisfies(a ->
                assertThat(a.getMoisSolvabiliteDate()).as("check moisSolvabiliteDate").isEqualTo(expected.getMoisSolvabiliteDate())
            )
            .satisfies(a ->
                assertThat(a.getCodeEtatSolvabilite()).as("check codeEtatSolvabilite").isEqualTo(expected.getCodeEtatSolvabilite())
            )
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultatSolvableUpdatableRelationshipsEquals(ResultatSolvable expected, ResultatSolvable actual) {
        assertThat(actual)
            .as("Verify ResultatSolvable relationships")
            .satisfies(a -> assertThat(a.getRechercheSolvable()).as("check rechercheSolvable").isEqualTo(expected.getRechercheSolvable()));
    }
}
