package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SituationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSituationAllPropertiesEquals(Situation expected, Situation actual) {
        assertSituationAutoGeneratedPropertiesEquals(expected, actual);
        assertSituationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSituationAllUpdatablePropertiesEquals(Situation expected, Situation actual) {
        assertSituationUpdatableFieldsEquals(expected, actual);
        assertSituationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSituationAutoGeneratedPropertiesEquals(Situation expected, Situation actual) {
        assertThat(actual)
            .as("Verify Situation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSituationUpdatableFieldsEquals(Situation expected, Situation actual) {
        assertThat(actual)
            .as("Verify Situation relevant properties")
            .satisfies(a ->
                assertThat(a.getSituationProDebutDate()).as("check situationProDebutDate").isEqualTo(expected.getSituationProDebutDate())
            )
            .satisfies(a ->
                assertThat(a.getSituationProfinDate()).as("check situationProfinDate").isEqualTo(expected.getSituationProfinDate())
            )
            .satisfies(a -> assertThat(a.getCodeSituation()).as("check codeSituation").isEqualTo(expected.getCodeSituation()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()))
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSituationUpdatableRelationshipsEquals(Situation expected, Situation actual) {
        assertThat(actual)
            .as("Verify Situation relationships")
            .satisfies(a -> assertThat(a.getDebiteur()).as("check debiteur").isEqualTo(expected.getDebiteur()));
    }
}
