package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutAllPropertiesEquals(Statut expected, Statut actual) {
        assertStatutAutoGeneratedPropertiesEquals(expected, actual);
        assertStatutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutAllUpdatablePropertiesEquals(Statut expected, Statut actual) {
        assertStatutUpdatableFieldsEquals(expected, actual);
        assertStatutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutAutoGeneratedPropertiesEquals(Statut expected, Statut actual) {
        assertThat(actual)
            .as("Verify Statut auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutUpdatableFieldsEquals(Statut expected, Statut actual) {
        assertThat(actual)
            .as("Verify Statut relevant properties")
            .satisfies(a -> assertThat(a.getStatutDebutDate()).as("check statutDebutDate").isEqualTo(expected.getStatutDebutDate()))
            .satisfies(a -> assertThat(a.getStatutFinDate()).as("check statutFinDate").isEqualTo(expected.getStatutFinDate()))
            .satisfies(a -> assertThat(a.getCodeStatut()).as("check codeStatut").isEqualTo(expected.getCodeStatut()))
            .satisfies(a -> assertThat(a.getMotifStatut()).as("check motifStatut").isEqualTo(expected.getMotifStatut()))
            .satisfies(a -> assertThat(a.getCodeAgent()).as("check codeAgent").isEqualTo(expected.getCodeAgent()))
            .satisfies(a -> assertThat(a.getUserCreation()).as("check userCreation").isEqualTo(expected.getUserCreation()))
            .satisfies(a -> assertThat(a.getCreationDate()).as("check creationDate").isEqualTo(expected.getCreationDate()))
            .satisfies(a -> assertThat(a.getUserMaj()).as("check userMaj").isEqualTo(expected.getUserMaj()))
            .satisfies(a -> assertThat(a.getMajDate()).as("check majDate").isEqualTo(expected.getMajDate()))
            .satisfies(a -> assertThat(a.getNumMaj()).as("check numMaj").isEqualTo(expected.getNumMaj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatutUpdatableRelationshipsEquals(Statut expected, Statut actual) {
        assertThat(actual)
            .as("Verify Statut relationships")
            .satisfies(a -> assertThat(a.getDossier()).as("check dossier").isEqualTo(expected.getDossier()));
    }
}
